# Generated by Django 3.2.16 on 2024-02-09 10:32

from django.db import migrations, models
import users.functions


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Пользователь'), ('admin', 'Администратор'), ('moderator', 'Модератор')], default='user', max_length=9, verbose_name='роль пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, max_length=150, unique=True, validators=[users.functions.UserValidateMixin.validate_username], verbose_name='Имя пользователя'),
        ),
    ]
