# Generated by Django 3.2.16 on 2024-02-09 10:33

from django.db import migrations, models
import users.functions


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20240209_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[users.functions.UserValidateMixin.validate_username], verbose_name='Имя пользователя'),
        ),
    ]
