# Generated by Django 3.2 on 2024-01-31 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20240131_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'пользователь'), ('admin', 'администратор'), ('moderator', 'модератор')], default='user', max_length=20, verbose_name='роль пользователя'),
        ),
    ]
