# Generated by Django 3.2 on 2024-02-03 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20240203_1809'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reviews',
            name='unique review',
        ),
        migrations.AlterField(
            model_name='reviews',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='reviews.title', unique=True, verbose_name='произведение'),
        ),
        migrations.AddConstraint(
            model_name='reviews',
            constraint=models.UniqueConstraint(fields=('author', 'title'), name='unique_author_title'),
        ),
    ]
