# Generated by Django 3.2 on 2024-02-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20240203_1844'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reviews',
            name='unique_author_title',
        ),
        migrations.AddConstraint(
            model_name='reviews',
            constraint=models.UniqueConstraint(fields=('title', 'author'), name='unique_review'),
        ),
    ]
